version: "3"
services:
  l2tp_fav:
    #image: ubergarm/l2tp-ipsec-vpn-client
    build:
        context: .
        dockerfile: ./Dockerfile
    network_mode: "host"
    privileged: true
    restart: always
    environment:
      - VPN_SERVER_IPV4=${VPN_HOST}
      - VPN_PSK=${VPN_PSK}
      - VPN_USERNAME=${VPN_USER}
      - VPN_PASSWORD=${VPN_PASS}